[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
fuzz_runs = 10000

[profile.ci]
fuzz_runs = 100000
fuzz_max_local_rejects = 2
fuzz_max_global_rejects = 2
fallback_very_max_recursion = 10

[etherscan.sepolia]
key = "${ETHERSCAN_API_KEY}"
chain_id = 11155111

[rpc_endpoints.sepolia]
url = "${SEPOLIA_RPC_URL}"